# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sentiment-analysis
template:
  metadata:
    labels:
      app: sentiment-analysis
  spec:
    containers:
    - name: sentiment-analysis-container
      image: sentiment-analysis-service
      ports:
     - containerPort: 5000
